dwmkerr/effective-shell

README.md, content/_index.md, content/docs/section0/is-this-book-for-me/_index.md, content/docs/section3/_index.md, content/docs/section4/_index.md, content/docs/section5/_index.md, content/docs/section6/reading-list/_index.md, content/docs/section6/the-future/_index.md, content/menu/index.md
Also adds a bit more introduction information.
=> chore: cleanup of readme

CONTRIBUTING.md, style-guide.md
=> feat: added a more detailed style guide

README.md
=> feat: set license to cc-ba-nc-sa.

.gitignore, README.md, makefile
=> build(playground): add the playground to the downloads folder

website/content/docs/part-1-transitioning-to-the-shell/6-the-renaissance-of-the-shell/_index.md
This commit removes repeated paragraphs and a typo. It looks like the same 3-4 paragraphs were pasted twice. 
This commit makes stylistic changes to create more variety in how we start each paragraph in the DevOps section.
=> Remove typos, add style changes.

.github/workflows/main.yml, website/content/docs/part-1-transitioning-to-the-shell/3-managing-your-files/_index.md
=> feat: build on all branches

website/content/docs/part-2-core-skills/2-thinking-in-pipelines/_index.md
=> fix: remove trailing backslash

.gitignore, structure.md, website/content/docs/part-3-manipulating-text-and-streams/12-get-to-grips-with-grep/_index.md
=> fix(chapter-12): improvements to the grep chapter

README.md, style-guide.md
* New possible title in [README](README.md)
* Fixes to minor typos in [README](README.md)
* Fixes to minor typos in the [style guide](style-guide.md)
* Introduces `\` for line breaks where missing in [README](README.md)
=> Title suggestion, typo fixes in README and style-guide

website/content/docs/part-2-core-skills/fly-on-the-command-line/_index.md
=> fix: correct bindkey in fly on the command line

README.md, website/content/docs/part-3-manipulating-text/regex-essentials/_index.md
=> feat: regex essentials

README.md
=> docs: added 'release please' status badge

effective-shell-playground/pictures/.backup-notes, makefile, structure.md
=> feat(samples): added a hidden file to the pictures samples folder to support chapter 2

effective-shell-playground/websites/simple/code.js, effective-shell-playground/websites/simple/index.html
If the site doesn't load properly a warning is shown.
❗ Important ❗
=> feat(samples): improve simple website sample

structure.md, website/content/docs/part-4-shell-scripting/logic/_index.md, website/content/docs/part-4-shell-scripting/variables-reading-input-and-mathematics/_index.md, website/content/menu/index.md
=> feat: chapter 19 variables, reading input, and mathematics

scripts/common.sh, scripts/common.v2.sh, scripts/common.v3.sh, structure.md, website/content/docs/part-4-shell-scripting/logic/_index.md, website/content/docs/part-4-shell-scripting/mastering-the-if-statement/_index.md, website/content/docs/part-4-shell-scripting/shell-script-essentials/_index.md, website/content/docs/part-4-shell-scripting/variables-reading-input-and-mathematics/_index.md, website/content/menu/index.md
=> feat: chapter 20 - mastering if the if statement

website/content/docs/part-4-shell-scripting/variables-reading-input-and-mathematics/_index.md
=> fix: fix index messing with formatting

website/content/docs/part-4-shell-scripting/logic/_index.md, website/content/docs/part-4-shell-scripting/mastering-the-if-statement/_index.md
=> fix: typo in title

README.md, sharing.md, structure.md
=> refactor: move titles/publisherinfo out of the readme

structure.md, website/content/docs/part-4-shell-scripting/functions-parameters-and-error-handling/_index.md, website/content/docs/part-4-shell-scripting/mastering-conditional-logic/_index.md, website/content/docs/part-4-shell-scripting/useful-patterns-for-shell-scripts/_index.md, website/content/docs/part-4-shell-scripting/variables-reading-input-and-mathematics/_index.md, website/content/docs/part-5-building-your-toolkit/configuring-the-shell/configuring-the-shell/_index.md, website/content/docs/part-x-appendices/essential-manpages.md, website/content/docs/part-x-appendices/shell-parameter-expansion.md, website/content/menu/index.md
=> fix: cleanup of 'mastering conditional logic' chapter

effective-shell-playground/scripts/set_ps1.sh, structure.md, style-guide.md, website/content/docs/part-5-building-your-toolkit/customising-your-command-prompt/_index.md, website/content/docs/part-x-appendices/essential-manpages.md, website/content/docs/part-x-appendices/index-of-commands.md, website/content/menu/index.md
=> wip: preparation work on 'customise your command prompt'

website/content/docs/getting-started/_index.md
=> Typo corrected

website/content/docs/part-2-core-skills/thinking-in-pipelines/_index.md
=> correct "sd" to "sed"

website/content/docs/part-2-core-skills/thinking-in-pipelines/_index.md
=> Add missing "D" in "Dogs"

README.md, effective-shell/docs/01-transitioning-to-the-shell/01-getting-started/index.md, effective-shell/docs/01-transitioning-to-the-shell/02-navigating-your-system/index.md, effective-shell/docs/01-transitioning-to-the-shell/03-managing-your-files/index.md, effective-shell/docs/01-transitioning-to-the-shell/04-clipboard-gymnastics/index.md, effective-shell/docs/01-transitioning-to-the-shell/05-getting-help/index.md, effective-shell/docs/01-transitioning-to-the-shell/index.md, effective-shell/docs/01-transitioning-to-the-shell/the-renaissance-of-the-shell/index.md
=> fix: fixup relative paths for docusaurus and slugs

.github/workflows/release-please.yaml
=> fix: use latest release please action

docusaurus.config.js
=> fix: update to new gtag id

README.md, docs/06-advanced-techniques/30-how-to-avoid-scripting/index.md, samples/programs/lookup/lookup-v2.py
=> docs: suggestions for python cli packages

README.md
=> docs: credits for asciinema

docs/06-advanced-techniques/31-the-secure-shell/index.mdx
=> wip: proofing chapter 30

docs/02-core-skills/07-thinking-in-pipelines/index.md
Fixed a typo in Chapter 07 ("Standing" -> "Standard")
❗ Important ❗
=> Fixed typo

docs/01-transitioning-to-the-shell/01-getting-started/index.md, docs/index.mdx
❗ Important ❗
No problem on the above.
I found _Effective Shell_ today and have been enjoying reading it. I'll be recommending it to my team.
=> Improve grammar

docs/02-core-skills/11-finding-files/index.md
=> Add 3 to maxdepth

docs/02-core-skills/08-fly-on-the-command-line/index.md
=> Fix capitalization.

docs/04-shell-scripting/20-mastering-conditional-logic/index.md
=> docs: fix typo

.github/workflows/pull-request.yaml, .github/workflows/release-please.yaml, docusaurus.config.js, makefile, package-lock.json, package.json, tsconfig.json
=> build: fix checkout action version

docs/06-advanced-techniques/32-a-vim-crash-course/index.mdx
=> docs: corrections for vim chapter

docs/04-shell-scripting/20-mastering-conditional-logic/index.md
=> fix: correct typo in test command

docs/xx-appendices/recommended-reading/index.mdx
=> docs: recommended reading updates

docs/index.mdx
=> docs(intro): improve intro page

docs/03-manipulating-text/17-build-commands-on-the-fly/index.md
=> remove stray example

docs/04-shell-scripting/18-shell-script-essentials/index.md
=> remove redundant can

docs/04-shell-scripting/18-shell-script-essentials/index.md, docs/04-shell-scripting/20-mastering-conditional-logic/index.md
=> fix typo (#260)

docs/01-transitioning-to-the-shell/04-clipboard-gymnastics/index.md
=> Duplicate word in 04-clipboard-gymnastics markdown

docs/04-shell-scripting/21-loops-and-working-with-files-and-folders/index.md
=> fix loop typos

docs/04-shell-scripting/18-shell-script-essentials/index.md
=> fix typo in shell chapter

docs/03-manipulating-text/13-regex-essentials/index.md
=> fix: correct email formatting

docs/04-shell-scripting/21-loops-and-working-with-files-and-folders/index.md
=> fix: correct grammar in loops chapter

docs/04-shell-scripting/23-useful-patterns-for-shell-scripts/index.md
=> Correct variable syntax in trap example

docusaurus.config.js
=> feat: adsense meta tag

scripts/build-samples.sh
=> fix: the samples for chapters 27 and 28 no longer contain .git folders

scripts/build-samples.sh
=> fix: correct name of dot git folder for samples tarball

samples/data/data.dat, samples/scripts/generate-data.sh
=> feat: add data file to samples

docs/05-building-your-toolkit/24-configuring-the-shell/index.md
=> feat: added alias for 'rm' sample

docs/00-index.mdx, docs/03-manipulating-text/16-advanced-text-manipulation/index.md, docs/xx-appendices/01-installing-samples/index.mdx
=> feat: appendix - installing the samples

sidebars.js
=> fix: appendices links

sidebars.js
=> fix: correct sidebar

makefile, scripts/build-samples.sh
=> fix: rename 'samples' to 'effective-shell'

docs/xx-appendices/01-installing-samples/index.mdx, makefile, scripts/build-samples.sh
=> fix: consistent samples path

samples/data/email-addresses.txt
=> fix: missing line in sample file

docs/04-shell-scripting/20-mastering-conditional-logic/index.md
=> Fix a typo

docs/06-advanced-techniques/31-the-secure-shell/diagrams/asymmetric-encryption-share-secret.drawio, package-lock.json, scripts/build-samples.sh
=> fix: correct build script

samples/scripts/common.v1.sh, samples/scripts/common.v2.sh, samples/scripts/common.v3.sh, samples/scripts/common.v4.sh, samples/scripts/common.v5.sh
=> fix: title lines in common scripts, fixes #357

samples/programs/lookup/lookup-v1.py, samples/programs/lookup/lookup-v2.py, samples/programs/lookup/lookup-v3.py, samples/programs/lookup/lookup.py
=> fix: python sample bug

docs/00-index.mdx, docusaurus.config.js
=> docs: terminal ai links

docs/00-index.mdx
Adds a paragraph emphasizing the adaptability of technologists and the book's focus on tailoring the shell to individual needs.  Includes a link to pre-order the book on Amazon, with an image.  Minor re-ordering of content for clarity.
❗ Important ❗
=> docs: Improve introduction and add Amazon link
